### List All Mesages
GET http://localhost:3333/users
Content-Type: application/json

### Create a new message
POST http://localhost:3333/users
Content-Type: application/json

{
  "name":"Victor Magaldi 2204",
  "email":"victor.teste@gmail.com"
}

### Delete message 
DELETE http://localhost:3333/users/a3e3d756-a97f-4e49-b987-da247b508746